// ================= CONTEXTO MODULO =================
// Catalogo estatico de recetas y fallback.
// Fuente de datos para sugerencias segun coincidencia de ingredientes.

export const RECIPE_CATEGORIES = [
    { id: "para-ti",     label: "Para ti"     },
    { id: "jugos",       label: "Jugos"        },
    { id: "cocteles",    label: "Cocteles"     },
    { id: "ensaladas",   label: "Ensaladas"    },
    { id: "proteinas",   label: "Proteínas"    },
    { id: "sandwiches",  label: "Sandwiches"   },
    { id: "pasta",       label: "Pasta & Arroz"},
    { id: "sopas",       label: "Sopas"        },
];

export const RECIPE_CATALOG = [

    // ===== HUEVOS Y TORTILLAS =====
    {
        id: "omelette-queso",
        title: "Omelette de queso",
        category: "proteinas",
        time: "12 min",
        servings: 1,
        imageQuery: "cheese omelette eggs pan",
        ingredients: ["huevo", "queso", "cebolla"],
        steps: [
            "Rompe 3 huevos en un bowl, añade sal y pimienta negra recién molida. Bate enérgicamente con un tenedor durante 30 segundos hasta que la mezcla sea completamente uniforme y veas pequeñas burbujas en la superficie.",
            "Pica finamente un cuarto de cebolla. Calienta una sartén de 20-22 cm a fuego medio-bajo, derrite 1 cucharada de mantequilla y sofríe la cebolla 3-4 minutos hasta que esté translúcida y brillante, sin que tome color.",
            "Sube el fuego a medio-alto. Vierte los huevos batidos sobre la cebolla. Cuando los bordes comiencen a cuajar (unos 20 segundos), usa una espátula de silicona para jalar los bordes cocidos hacia el centro, dejando que el huevo líquido fluya hacia los lados. Repite 2-3 veces.",
            "Cuando el centro esté apenas cuajado pero todavía brillante y húmedo, distribuye el queso rallado sobre una mitad del omelette. Dobla con la espátula y desliza inmediatamente al plato. El calor residual terminará de fundir el queso — no lo cocines en exceso.",
        ],
    },
    {
        id: "huevos-revueltos-jamon",
        title: "Huevos revueltos con jamón",
        category: "proteinas",
        time: "10 min",
        servings: 1,
        imageQuery: "scrambled eggs ham cheese breakfast",
        ingredients: ["huevo", "jamon", "queso"],
        steps: [
            "Bate 3 huevos con una pizca de sal y pimienta. Para huevos más cremosos, añade 1 cucharada de leche o crema al batir.",
            "Calienta una sartén a fuego medio-bajo con una pequeña cantidad de mantequilla. Agrega el jamón en cubos pequeños y dóralo 1 minuto hasta que selle los bordes sin resecarse.",
            "Vierte los huevos batidos sobre el jamón. Con una espátula de silicona, mueve suavemente los huevos en círculos amplios desde los bordes hacia el centro. La clave es fuego bajo y paciencia: 3-4 minutos para huevos muy cremosos.",
            "Justo antes de que terminen de cuajar (cuando aún se vean ligeramente húmedos), retira del fuego y agrega el queso rallado. El calor residual terminará la cocción y fundirá el queso. Sirve de inmediato.",
        ],
    },
    {
        id: "tortilla-espinaca-queso",
        title: "Tortilla de espinaca y queso",
        category: "proteinas",
        time: "18 min",
        servings: 2,
        imageQuery: "spinach cheese omelette frittata",
        ingredients: ["huevo", "espinaca", "queso"],
        steps: [
            "Saltea un puñado generoso de espinaca fresca en sartén con un poco de aceite durante 2 minutos hasta que reduzca y pierda el exceso de agua. Escurre bien y reserva.",
            "Bate 4 huevos con sal, pimienta y la mitad del queso rallado. Incorpora la espinaca escurrida y mezcla uniformemente.",
            "En la misma sartén (22-24 cm) con un poco de aceite a fuego medio-bajo, vierte la mezcla. Cocina sin mover durante 4-5 minutos hasta que los bordes estén firmes y el centro empiece a cuajar.",
            "Esparce el queso restante por encima y tapa la sartén 2 minutos para que el vapor lo funda. Alternativamente, pasa 1-2 minutos bajo el grill del horno. Desliza a un plato y sirve en cuñas.",
        ],
    },
    {
        id: "frittata-zapallo-cebolla",
        title: "Frittata de zapallo y cebolla",
        category: "proteinas",
        time: "25 min",
        servings: 2,
        imageQuery: "pumpkin onion frittata eggs",
        ingredients: ["huevo", "zapallo", "cebolla"],
        steps: [
            "Precalienta el horno a 200°C. Corta 150g de zapallo y media cebolla en cubos de 1 cm. Saltea en sartén apta para horno con aceite a fuego medio-alto durante 6-8 minutos hasta que el zapallo esté dorado en los bordes.",
            "Bate 4 huevos con sal, pimienta y una pizca de nuez moscada. Agrega las verduras salteadas a los huevos y mezcla.",
            "En la misma sartén a fuego medio-bajo, vierte la mezcla. Cocina 3-4 minutos hasta que los bordes cuajen pero el centro siga líquido.",
            "Lleva la sartén al horno 8-10 minutos hasta que el centro esté firme y la superficie esté dorada. Deja reposar 3 minutos antes de cortar — esto facilita el desmolde y mejora la textura.",
        ],
    },
    {
        id: "revuelto-champinon-queso",
        title: "Revuelto de champiñón y queso",
        category: "proteinas",
        time: "12 min",
        servings: 1,
        imageQuery: "mushroom cheese scrambled eggs",
        ingredients: ["huevo", "champinon", "queso"],
        steps: [
            "Lamina 5-6 champiñones. Saltéalos en sartén con aceite a fuego alto durante 4-5 minutos hasta que estén bien dorados y sin líquido visible. El secreto: no muevas los hongos por los primeros 2 minutos para que se caramelicen.",
            "Baja el fuego a medio-bajo. Bate 3 huevos con sal y pimienta y viértelos sobre los champiñones.",
            "Mueve suavemente con espátula de silicona desde los bordes hacia el centro, como formando grandes trozos cremosos. Este proceso debería tomar 2-3 minutos — el fuego bajo evita que el huevo quede gomoso.",
            "Cuando queden apenas húmedos, agrega el queso rallado, retira del fuego y mezcla. Sirve de inmediato antes de que pierdan la cremosidad.",
        ],
    },
    {
        id: "shakshuka-rapida",
        title: "Shakshuka rápida",
        category: "proteinas",
        time: "20 min",
        servings: 2,
        imageQuery: "shakshuka eggs tomato sauce pan",
        ingredients: ["huevo", "tomate", "pimenton"],
        steps: [
            "Pica fino medio pimentón y 2 tomates maduros. Sofríe el pimentón con aceite a fuego medio 4 minutos hasta ablandar. Agrega los tomates, sal, comino y páprika ahumada al gusto. Cocina 8-10 minutos hasta obtener una salsa espesa.",
            "Prueba la salsa y ajusta la sazón. Debe estar bien sabrosa, pues los huevos la suavizarán. Si queda muy seca, añade un chorrito de agua.",
            "Con una cuchara, haz 3-4 huecos en la salsa. Rompe un huevo en cada hueco con cuidado de no romper la yema.",
            "Tapa la sartén y cocina a fuego medio-bajo 5-7 minutos. Para yemas líquidas retira a los 5 min; para más cocidas, a los 7. Sirve directamente en la sartén con pan para remojar en la salsa.",
        ],
    },
    {
        id: "huevos-benedictinos",
        title: "Huevos benedictinos",
        category: "proteinas",
        time: "20 min",
        servings: 2,
        imageQuery: "eggs benedict poached ham brunch",
        ingredients: ["huevo", "jamon", "pan"],
        steps: [
            "Tuesta el pan en la tostadora hasta que esté dorado y crujiente. Calienta el jamón en una sartén sin aceite 1-2 minutos por lado. Reserva ambos calientes.",
            "Calienta agua en una olla hasta que empiece a salir vapor pero sin hervir agresivamente (80-85°C). Agrega 1 cucharada de vinagre blanco — esto ayuda a que la clara coagule rápido.",
            "Rompe un huevo en un pocillo pequeño. Crea un remolino suave en el agua con una cuchara y desliza el huevo al centro. Cuece 3-4 minutos para yema líquida. Retira con espumadera y escurre sobre papel absorbente.",
            "Arma el plato en orden: pan tostado, jamón, huevo pochado. Sazona con sal, pimienta y, si tienes, una pizca de páprika. Sirve de inmediato pues el huevo se enfría rápido.",
        ],
    },

    // ===== ENSALADAS =====
    {
        id: "ensalada-caprese",
        title: "Ensalada caprese",
        category: "ensaladas",
        time: "10 min",
        servings: 2,
        imageQuery: "caprese salad tomato mozzarella basil",
        ingredients: ["tomate", "queso", "aceite"],
        steps: [
            "Usa tomates a temperatura ambiente — nunca fríos, pues el frío destruye su sabor. Córtalos en rodajas de 8mm. Haz lo mismo con el queso (mozzarella fresca ideal).",
            "En un plato amplio o tabla, alterna las rodajas de tomate y queso superpuestas ligeramente, formando una línea o espiral.",
            "Aliña justo antes de servir: aceite de oliva extra virgen con generosidad, sal de mar en escamas y pimienta negra recién molida. Si tienes hojas de albahaca fresca, rasga algunas con los dedos y distribúyelas por encima.",
            "Sirve de inmediato a temperatura ambiente. La ensalada caprese no se refrigera ni se prepara con mucha anticipación.",
        ],
    },
    {
        id: "ensalada-pollo-palta",
        title: "Ensalada de pollo y palta",
        category: "ensaladas",
        time: "15 min",
        servings: 2,
        imageQuery: "chicken avocado salad lettuce",
        ingredients: ["pollo", "palta", "lechuga"],
        steps: [
            "Si el pollo está crudo, sazona con sal y pimienta y cuécelo en sartén con aceite a fuego medio 5-6 minutos por lado hasta que esté bien cocido. Déjalo reposar 3 minutos y luego desmenuza con dos tenedores.",
            "Lava y seca bien la lechuga. Las hojas húmedas diluyen el aliño — usa papel absorbente o un centrifugador de ensalada. Rompe con las manos en trozos grandes.",
            "Corta la palta en mitades, retira el carozo y pela. Rebana en gajos de 1 cm. Riega con unas gotas de limón para evitar que se oxide.",
            "Mezcla el pollo con la lechuga. Prepara el aliño: 2 cucharadas de aceite de oliva, 1 cucharada de jugo de limón, sal y pimienta. Mezcla bien, vierte sobre la ensalada, agrega la palta por encima y sirve de inmediato.",
        ],
    },
    {
        id: "ensalada-atun-huevo",
        title: "Ensalada de atún y huevo",
        category: "ensaladas",
        time: "15 min",
        servings: 2,
        imageQuery: "tuna egg salad tomato",
        ingredients: ["atun", "huevo", "tomate"],
        steps: [
            "Hierve el huevo partiendo de agua fría. Cuando rompa hervor, cuece 9 minutos exactos para yema firme pero no harinosa. Enfría de inmediato en agua con hielo para detener la cocción y facilitar el pelado.",
            "Escurre bien el atún de la lata. Si tiene mucho aceite, pásalo por papel absorbente. Desmenúzalo con un tenedor en un bowl.",
            "Corta el tomate en cubos de 1 cm, escurriendo el exceso de jugo. Agrega al bowl con el atún. Pela y corta el huevo en cuartos.",
            "Aliña con aceite de oliva, jugo de limón, sal y pimienta. Mezcla suavemente para no romper el huevo. Sirve fresca, idealmente sobre hojas de lechuga.",
        ],
    },
    {
        id: "ensalada-griega",
        title: "Ensalada griega",
        category: "ensaladas",
        time: "12 min",
        servings: 2,
        imageQuery: "greek salad cucumber feta olives",
        ingredients: ["pepino", "tomate", "queso"],
        steps: [
            "Pela el pepino dejando algunas franjas de cáscara para textura. Córtalo en rodajas gruesas de 1 cm y luego en cuartos. El pepino no debe estar muy fino o la ensalada queda aguada.",
            "Corta los tomates en cuñas medianas. Escurre el exceso de jugo — esto mantiene la ensalada firme y evita que el aliño se diluya.",
            "Corta el queso (feta o de cabra) en cubos de 2 cm. Coloca todo en un bowl amplio: pepino, tomate y queso. Añade aceitunas negras si tienes.",
            "Aliña con abundante aceite de oliva extra virgen, orégano seco, sal y pimienta. Mezcla con suavidad para no desmenuzar el queso. Refrigera 5-10 minutos antes de servir para que los sabores se integren.",
        ],
    },
    {
        id: "ensalada-repollo-zanahoria",
        title: "Ensalada de repollo y zanahoria",
        category: "ensaladas",
        time: "15 min",
        servings: 3,
        imageQuery: "coleslaw cabbage carrot mayonnaise",
        ingredients: ["repollo", "zanahoria", "mayonesa"],
        steps: [
            "Corta el repollo en tiras muy finas con cuchillo o mandolina. Para suavizar su textura, añade sal, mezcla y deja reposar 5 minutos — luego exprime con las manos para eliminar el agua que suelta.",
            "Ralla la zanahoria en rallador grueso. Mezcla con el repollo ya escurrido en un bowl amplio.",
            "Prepara el aliño: 3 cucharadas de mayonesa, 1 cucharadita de mostaza, 1 cucharada de vinagre o jugo de limón, azúcar, sal y pimienta al gusto. Mezcla bien hasta integrar.",
            "Incorpora el aliño a las verduras y mezcla bien. Refrigera al menos 20 minutos antes de servir — este reposo es esencial para que el repollo ablande ligeramente y absorba el aliño.",
        ],
    },
    {
        id: "ensalada-frutas",
        title: "Ensalada de frutas",
        category: "ensaladas",
        time: "12 min",
        servings: 2,
        imageQuery: "fresh fruit salad bowl colorful",
        ingredients: ["manzana", "platano", "naranja"],
        steps: [
            "Pela y corta la manzana en cubos de 1.5 cm. Para evitar que se oxide, riégala de inmediato con jugo de naranja o limón.",
            "Pela el plátano y córtalo en rodajas de 1 cm. Pela y separa los gajos de la naranja eliminando la membrana blanca — esto mejora mucho la textura. Corta cada gajo en 2-3 trozos.",
            "Mezcla todas las frutas en un bowl. Agrega cualquier fruta adicional que tengas disponible: kiwi, frutillas, uvas, papaya.",
            "Aliña con el jugo que soltaron las frutas más un toque extra de limón y una pizca de azúcar si las frutas no están muy dulces. Refrigera 10-15 minutos antes de servir para que los sabores se integren.",
        ],
    },
    {
        id: "ensalada-garbanzos-fresca",
        title: "Ensalada fresca de garbanzos",
        category: "ensaladas",
        time: "10 min",
        servings: 2,
        imageQuery: "chickpea salad tomato cucumber fresh",
        ingredients: ["garbanzo", "tomate", "pepino"],
        steps: [
            "Si usas garbanzos de lata, escúrrelos y enjuágalos bajo agua fría. Sécalos con papel absorbente — los garbanzos húmedos diluyen el aliño.",
            "Corta 2 tomates medianos en cubos de 1 cm, escurriendo el jugo. Pela el pepino y córtalo también en cubos similares. La consistencia uniforme en los cortes hace la ensalada más agradable al comer.",
            "Mezcla garbanzos, tomate y pepino en un bowl. Si tienes, agrega media cebolla morada en pluma fina (remójala en agua fría 5 minutos para suavizar su picor).",
            "Aliña con aceite de oliva, jugo de limón generoso, sal, pimienta y comino al gusto. Mezcla bien y deja reposar 5 minutos. Sirve fría o a temperatura ambiente.",
        ],
    },
    {
        id: "ensalada-quinoa-palta",
        title: "Ensalada de quinoa y palta",
        category: "ensaladas",
        time: "20 min",
        servings: 2,
        imageQuery: "quinoa avocado salad healthy bowl",
        ingredients: ["quinoa", "palta", "tomate"],
        steps: [
            "Enjuaga 100g de quinoa bajo agua fría durante 1 minuto para eliminar la saponina que la hace amarga. Cocina con el doble de agua y una pizca de sal: lleva a hervor, baja el fuego al mínimo y tapa 12-15 minutos hasta que absorba toda el agua.",
            "Extiende la quinoa cocida en una fuente y deja enfriar completamente. La quinoa caliente ablanda los demás ingredientes y aguada la ensalada.",
            "Corta la palta en cubos de 2 cm y el tomate en cubos de 1 cm. Riega la palta con unas gotas de limón para evitar oxidación.",
            "Mezcla la quinoa fría con el tomate. Agrega la palta por encima con suavidad. Aliña con aceite de oliva, jugo de limón, sal y pimienta. Si tienes cilantro o perejil fresco, añade hojas al final.",
        ],
    },

    // ===== JUGOS Y BATIDOS =====
    {
        id: "batido-frutas",
        title: "Batido de frutas",
        category: "jugos",
        time: "8 min",
        servings: 1,
        imageQuery: "fruit smoothie banana strawberry milk",
        ingredients: ["leche", "platano", "frutilla"],
        steps: [
            "Pela 1 plátano maduro y córtalo en trozos. Los plátanos muy maduros (con manchas negras en la cáscara) dan más dulzor natural y cremosidad. Lava 6-8 frutillas y retira los cabos.",
            "Agrega la fruta a la licuadora. Si tienes las frutas congeladas, el batido saldrá más frío y espeso sin necesidad de hielo.",
            "Vierte 200ml de leche fría. Para un batido más espeso usa menos leche; para más líquido, añade más. Puedes sustituir leche por leche de avena o almendra.",
            "Licua a velocidad alta 30-40 segundos hasta que no queden trozos. Prueba el dulzor — si necesita más, añade 1 cucharadita de miel. Sirve de inmediato antes de que se separe.",
        ],
    },
    {
        id: "licuado-frutilla-yogur",
        title: "Licuado de frutilla y yogur",
        category: "jugos",
        time: "8 min",
        servings: 1,
        imageQuery: "strawberry yogurt smoothie drink",
        ingredients: ["frutilla", "yogur", "leche"],
        steps: [
            "Lava y desraba 150g de frutillas frescas. Si están muy maduras y dulces, úsalas directamente; si no, macéralas 5 minutos con 1 cucharadita de azúcar para potenciar su sabor.",
            "Agrega las frutillas a la licuadora junto con 150g de yogur natural (el griego da más cremosidad) y 100ml de leche fría.",
            "Licua 30 segundos a velocidad alta. El yogur espesa el licuado naturalmente, por lo que puede quedar bastante denso — ajusta la consistencia añadiendo leche de a poco.",
            "Sirve en vaso frío. Si lo quieres con espuma, licua 10 segundos más a alta velocidad justo antes de servir. Consume de inmediato para aprovechar la textura.",
        ],
    },
    {
        id: "smoothie-verde-fruta",
        title: "Smoothie verde",
        category: "jugos",
        time: "8 min",
        servings: 1,
        imageQuery: "green smoothie spinach banana",
        ingredients: ["espinaca", "platano", "leche"],
        steps: [
            "Para suavizar el sabor de la espinaca, usa un plátano bien maduro — su dulzor natural neutraliza el amargor de las hojas verdes. Pela y trocea el plátano.",
            "Agrega un puñado grande de espinaca fresca (40-50g) a la licuadora. Si tienes espinaca congelada funciona igual de bien y hace el smoothie más frío.",
            "Añade el plátano y 200ml de leche fría. Para versión más espesa y nutritiva, incluye 1 cucharada de mantequilla de maní o una cucharada de avena.",
            "Licua a máxima velocidad 45 segundos para que la espinaca quede completamente triturada y no se note textura. El color verde intenso es señal de buena licuación. Sirve de inmediato.",
        ],
    },
    {
        id: "bowl-yogur-fruta",
        title: "Bowl de yogur y fruta",
        category: "jugos",
        time: "8 min",
        servings: 1,
        imageQuery: "yogurt fruit bowl banana apple",
        ingredients: ["yogur", "platano", "manzana"],
        steps: [
            "Usa yogur griego natural sin azúcar — su textura espesa es la base ideal. Sirve 200g en un bowl amplio y frío (guárdalo 5 min en el freezer).",
            "Pela y corta el plátano en rodajas de 1 cm. Corta la manzana en cubos pequeños con cáscara para más fibra y color. Riégala con unas gotas de limón para evitar oxidación.",
            "Distribuye la fruta visualmente sobre el yogur: crea secciones o filas en lugar de mezclar todo. La presentación hace que se vea más apetitoso.",
            "Termina con toppings si tienes: granola para textura crujiente, miel para dulzor, semillas de chía o linaza para nutrición extra. Come de inmediato para que la granola no se ablande.",
        ],
    },
    {
        id: "avena-nocturna-yogur",
        title: "Avena nocturna con yogur",
        category: "jugos",
        time: "5 min + reposo",
        servings: 1,
        imageQuery: "overnight oats yogurt apple jar",
        ingredients: ["yogur", "leche", "manzana"],
        steps: [
            "En un frasco o recipiente hermético, mezcla 50g de avena en hojuelas con 100ml de leche, 100g de yogur griego y una pizca de sal. La proporción avena:líquido de 1:2 da una consistencia cremosa — ajusta según preferencia.",
            "Agrega 1 cucharadita de miel o azúcar, canela al gusto y, si tienes, 1 cucharada de semillas de chía para espesar más y añadir nutrientes.",
            "Mezcla todo bien, tapa el frasco y refrigera toda la noche (mínimo 6 horas). La avena absorbe el líquido y se ablanda completamente.",
            "Por la mañana, revuelve la mezcla. Pela y corta la manzana en cubos pequeños y agrégala encima. Añade más leche si la consistencia quedó muy espesa. Consume fría directamente del frasco.",
        ],
    },
    {
        id: "jugo-naranja-zanahoria",
        title: "Jugo de naranja y zanahoria",
        category: "jugos",
        time: "10 min",
        servings: 1,
        imageQuery: "orange carrot juice fresh drink",
        ingredients: ["naranja", "zanahoria", "limon"],
        steps: [
            "Pela 2 naranjas y exprime su jugo. Para más rendimiento, rueda las naranjas sobre la superficie presionando antes de cortarlas. Reserva el jugo.",
            "Pela 1 zanahoria mediana y córtala en trozos. Licúala con 60ml de agua hasta que quede completamente triturada, luego cuela con colador fino o tela para obtener solo el jugo.",
            "Mezcla el jugo de naranja con el jugo de zanahoria colado. Agrega el jugo de medio limón recién exprimido — esto realza el sabor y actúa como preservante natural.",
            "Sirve en vaso alto con abundante hielo. No refrigeres por más de 1 hora, pues los jugos frescos pierden sus vitaminas rápidamente.",
        ],
    },
    {
        id: "limonada-menta",
        title: "Limonada con menta",
        category: "jugos",
        time: "10 min",
        servings: 2,
        imageQuery: "lemonade mint ice cold drink",
        ingredients: ["limon", "menta", "agua"],
        steps: [
            "Prepara almíbar simple: disuelve 4 cucharadas de azúcar en 60ml de agua caliente, revolviendo hasta que no queden cristales. Déjalo enfriar — esto da dulzor uniforme sin que el azúcar quede en el fondo.",
            "Exprime el jugo de 3-4 limones (unos 100ml). Para más aroma, ralla un poco de la cáscara de limón antes de exprimir y añádela al almíbar.",
            "En una jarra, mezcla el jugo de limón con el almíbar frío y 400ml de agua fría. Ajusta el dulzor y acidez a tu gusto — la limonada perfecta balancea los dos.",
            "Agrega 8-10 hojas de menta fresca y machúcalas suavemente dentro de la jarra para liberar los aceites aromáticos sin romperlas. Añade hielo generosamente y sirve de inmediato.",
        ],
    },

    // ===== SANDWICHES Y WRAPS =====
    {
        id: "sandwich-pollo",
        title: "Sándwich de pollo",
        category: "sandwiches",
        time: "15 min",
        servings: 1,
        imageQuery: "chicken sandwich tomato bread",
        ingredients: ["pollo", "pan", "tomate"],
        steps: [
            "Si el pollo está crudo, aplástalo a grosor uniforme con la palma de la mano. Sazona con sal, pimienta y ajo en polvo. Cocina en sartén caliente con poco aceite 4-5 minutos por lado hasta que esté bien dorado y cocido. Deja reposar 2 minutos antes de cortar.",
            "Tuesta el pan hasta que esté dorado y crujiente. Un buen tostado evita que el pan se empape con los jugos del pollo y el tomate.",
            "Prepara el tomate: córtalo en rodajas de 5mm y sécalas con papel absorbente. El tomate húmedo reblandece el pan.",
            "Arma el sándwich: unta mayonesa o palta aplastada en ambas tapas del pan. Coloca el pollo, luego el tomate y lechuga si tienes. Cierra y sirve de inmediato o envuelve en papel para llevarlo.",
        ],
    },
    {
        id: "sandwich-pavo-queso",
        title: "Sándwich de pavo y queso",
        category: "sandwiches",
        time: "10 min",
        servings: 1,
        imageQuery: "turkey cheese sandwich toasted",
        ingredients: ["pavo", "queso", "pan"],
        steps: [
            "Arma el sándwich en frío primero: coloca 2-3 láminas de pavo sobre una tapa del pan y cubre con queso en láminas. Asegúrate de que el queso cubra bien el pavo para que funda de manera uniforme.",
            "Para hacerlo caliente (tipo grilled cheese), úntale mantequilla por fuera a ambas tapas del pan armado. Esto da un dorado perfecto y sabor.",
            "Cocina en sartén a fuego medio 2-3 minutos por lado presionando suavemente con una espátula. Cuando el pan esté dorado y crujiente y el queso fundido, está listo.",
            "Deja reposar 1 minuto antes de cortar en diagonal — esto evita que el queso se derrame y hace el sándwich más manejable. Sirve caliente.",
        ],
    },
    {
        id: "quesadilla-jamon-queso",
        title: "Quesadilla de jamón y queso",
        category: "sandwiches",
        time: "10 min",
        servings: 1,
        imageQuery: "ham cheese quesadilla mexican",
        ingredients: ["jamon", "queso", "tortilla"],
        steps: [
            "Ralla o corta el queso en láminas finas para que funda rápido y de manera uniforme. Usa queso que funda bien: gauda, mozzarella, mantecoso o cheddar.",
            "Distribuye el jamón en cubos o tiras sobre la mitad de una tortilla de trigo. Cubre el jamón con abundante queso. Dobla la tortilla en semicírculo presionando suavemente.",
            "Calienta una sartén grande a fuego medio sin aceite (o con unas gotas). Coloca la quesadilla y cocina 2-3 minutos hasta que el lado inferior esté dorado y ligeramente crujiente.",
            "Voltea con cuidado usando una espátula amplia y cocina 2 minutos más. El queso debe estar completamente fundido y los bordes sellados. Retira, espera 1 minuto y corta en triángulos con cuchillo o tijera. Sirve con guacamole o crema ácida si tienes.",
        ],
    },
    {
        id: "tostada-ricota-tomate",
        title: "Tostada de ricota y tomate",
        category: "sandwiches",
        time: "8 min",
        servings: 1,
        imageQuery: "ricotta tomato toast bread",
        ingredients: ["ricota", "tomate", "pan"],
        steps: [
            "Tuesta el pan a tu nivel de dorado preferido. Para esta tostada funciona mejor pan de masa madre, ciabatta o pan rústico — su textura aguanta mejor los toppings húmedos.",
            "Mezcla la ricota con sal, pimienta y un chorrito de aceite de oliva para mejorar su sabor y untabilidad. Unta generosamente sobre el pan tostado.",
            "Corta el tomate en rodajas de 5mm y sécalas con papel absorbente. Colócalas superpuestas sobre la ricota.",
            "Termina con aceite de oliva extra virgen en hilo, sal de mar en escamas y pimienta negra recién molida. Si tienes albahaca fresca u orégano seco, añade encima. Sirve de inmediato.",
        ],
    },
    {
        id: "wrap-huevo-espinaca",
        title: "Wrap de huevo y espinaca",
        category: "sandwiches",
        time: "12 min",
        servings: 1,
        imageQuery: "egg spinach wrap tortilla",
        ingredients: ["huevo", "espinaca", "tortilla"],
        steps: [
            "Calienta la tortilla en sartén seca 30 segundos por lado hasta que esté flexible y con pequeñas manchas doradas. Envuélvela en papel de cocina para mantenerla caliente y suave.",
            "Saltea un puñado de espinaca en sartén con aceite y ajo en polvo 2 minutos hasta reducir. Escurre bien para que no humedezca el wrap.",
            "En la misma sartén, bate 2 huevos con sal y pimienta y haz un revuelto cremoso a fuego bajo. Retira cuando todavía estén ligeramente húmedos.",
            "Extiende la tortilla, coloca el revuelto de huevo en el centro y la espinaca encima. Dobla los extremos laterales hacia adentro y enrolla firmemente desde el extremo más cercano. Corta en diagonal y sirve.",
        ],
    },
    {
        id: "pizza-pan-molde",
        title: "Pizza rápida en pan de molde",
        category: "sandwiches",
        time: "12 min",
        servings: 1,
        imageQuery: "bread pizza cheese tomato quick",
        ingredients: ["pan", "queso", "tomate"],
        steps: [
            "Precalienta el horno a 220°C o el grill al máximo. La temperatura alta es clave para fundir el queso rápido sin resecar el pan.",
            "Pon 2 rebanadas de pan en bandeja. Aplasta el tomate cortado con un tenedor sobre el pan o usa salsa de tomate si tienes. Sazona con orégano, sal y un hilo de aceite.",
            "Cubre generosamente con queso rallado. No escatimes en el queso — una capa gruesa da el efecto fundido y dorado característico de la pizza.",
            "Hornea 6-8 minutos hasta que el queso esté completamente fundido y con manchas doradas. Vigila los últimos 2 minutos para evitar que se queme. Deja reposar 1 minuto y agrega más orégano antes de servir.",
        ],
    },
    {
        id: "completo-italiano",
        title: "Completo italiano",
        category: "sandwiches",
        time: "10 min",
        servings: 1,
        imageQuery: "hot dog avocado tomato chilean",
        ingredients: ["pan", "tomate", "palta"],
        steps: [
            "Calienta el pan de completo en el horno o parrilla hasta que esté tibio y ligeramente crujiente por fuera. Un completo con pan caliente es mucho mejor.",
            "Aplasta la palta madura con tenedor. Añade sal, limón y una pizca de ají si te gusta. La consistencia ideal es cremosa pero con algunos trozos, no un puré liso.",
            "Pica el tomate en cubos pequeños de 5mm. Escurre el líquido sobrante con un colador unos segundos para que no moje el pan.",
            "Arma el completo en orden: primero una capa de palta aplastada, luego el tomate picado y finalmente mayonesa al gusto. El orden importa para que no se mezcle todo. Sirve de inmediato.",
        ],
    },

    // ===== CARNES Y PROTEINAS =====
    {
        id: "salteado-verduras",
        title: "Salteado de verduras",
        category: "proteinas",
        time: "15 min",
        servings: 2,
        imageQuery: "colorful vegetable stir fry pan",
        ingredients: ["zanahoria", "pimenton", "cebolla"],
        steps: [
            "Corta todas las verduras en tiras finas y uniformes de 5cm — el corte consistente asegura cocción pareja. Ten todo listo antes de encender el fuego, el salteado va rápido.",
            "Calienta el wok o sartén más grande que tengas a fuego muy alto hasta que humee ligeramente. Agrega aceite con punto de humo alto (girasol, canola o maravilla — nunca oliva extra virgen a fuego alto).",
            "Agrega primero la cebolla y pimentón 2 minutos sin mover para que se caramelicen. Luego la zanahoria 2 minutos más. El fuego alto y no mover es lo que da el sabor característico del salteado.",
            "Sazona con salsa de soja, sal, pimienta y ajo en polvo. Saltea 1 minuto más mezclando todo. Las verduras deben quedar tiernas pero con mordida — no blandas. Sirve de inmediato como acompañamiento.",
        ],
    },
    {
        id: "pollo-salteado-brocoli",
        title: "Pollo salteado con brócoli",
        category: "proteinas",
        time: "18 min",
        servings: 2,
        imageQuery: "chicken broccoli stir fry wok",
        ingredients: ["pollo", "brocoli", "cebolla"],
        steps: [
            "Corta el pollo en tiras finas de 1cm de grosor. Sazona con sal, pimienta y 1 cucharadita de maicena — esto crea una capa protectora que mantiene el pollo jugoso al saltear.",
            "Separa el brócoli en floretes pequeños. Blanquéalos 2 minutos en agua hirviendo con sal y pásalos de inmediato a agua con hielo para fijar el color verde brillante. Escurre bien.",
            "En wok o sartén grande muy caliente con aceite, saltea el pollo a fuego alto 4-5 minutos hasta que esté dorado y cocido. Retira y reserva. En la misma sartén, saltea la cebolla en pluma 2 minutos.",
            "Regresa el pollo, agrega el brócoli y saltea todo junto 1-2 minutos. Agrega salsa de soja y un poco de aceite de sésamo si tienes. Sirve sobre arroz blanco.",
        ],
    },
    {
        id: "pollo-yogur-limon",
        title: "Pollo al yogur y limón",
        category: "proteinas",
        time: "30 min",
        servings: 2,
        imageQuery: "lemon yogurt chicken grilled",
        ingredients: ["pollo", "yogur", "limon"],
        steps: [
            "Prepara la marinada: mezcla 150g de yogur natural con el jugo y ralladura de 1 limón, 2 dientes de ajo rallados, sal, pimienta, orégano y páprika. El yogur tierniza la carne durante el marinado.",
            "Haz cortes diagonales de 1cm de profundidad en el pollo — esto permite que la marinada penetre mejor. Cubre completamente con la mezcla y deja marinar mínimo 20 minutos (o toda la noche en el refrigerador).",
            "Cocina en sartén a fuego medio-alto con un chorrito de aceite, 5-6 minutos por lado hasta que el exterior esté bien dorado y el interior cocido. No muevas el pollo los primeros 3 minutos para que selle correctamente.",
            "Deja reposar el pollo 3-4 minutos cubierto con papel aluminio antes de servir. Este reposo redistribuye los jugos internos y evita que se resequen al cortar. Acompaña con ensalada fresca y pan de pita si tienes.",
        ],
    },
    {
        id: "salmon-limon-mantequilla",
        title: "Salmón con limón",
        category: "proteinas",
        time: "15 min",
        servings: 2,
        imageQuery: "lemon butter salmon fillet cooked",
        ingredients: ["salmon", "limon", "mantequilla"],
        steps: [
            "Seca muy bien el salmón con papel absorbente — la humedad en la superficie impide el dorado. Sazona con sal y pimienta solo justo antes de cocinar.",
            "Calienta sartén a fuego medio-alto. Agrega un poco de aceite y cuando esté bien caliente (verás que humea ligeramente), coloca el salmón con la piel hacia abajo. Presiona suavemente 30 segundos con espátula para que la piel quede plana.",
            "Cocina 4-5 minutos sin mover hasta que veas que la cocción sube por los costados (el color rosado avanza de abajo hacia arriba). Voltea solo una vez y cocina 1-2 minutos más. El salmón perfecto tiene el centro ligeramente traslúcido.",
            "Con el fuego apagado, agrega 1 cucharada de mantequilla y rodajas de limón a la sartén. Cuando la mantequilla se derrita, úsala para bañar el salmón con una cuchara 30 segundos. Sirve de inmediato.",
        ],
    },
    {
        id: "lomo-saltado",
        title: "Lomo saltado",
        category: "proteinas",
        time: "20 min",
        servings: 2,
        imageQuery: "beef stir fry tomato onion peruvian",
        ingredients: ["carne", "tomate", "cebolla"],
        steps: [
            "Corta la carne en tiras de 1cm de grosor, siguiendo la dirección contraria a la fibra muscular — esto la hace más tierna. Sazona con sal, pimienta, ajo en polvo y 1 cucharada de soja.",
            "Calienta el wok o sartén a fuego máximo hasta que humee. Agrega aceite y sella las tiras de carne en tandas pequeñas, 1-2 minutos por lado sin mover. Cocinar de a poco evita que se cuezan al vapor en lugar de dorarse.",
            "En la misma sartén, saltea la cebolla en pluma gruesa 2 minutos a fuego alto. Agrega el tomate en gajos gruesos y saltea 1 minuto más — el tomate debe quedar cálido pero sin deshacerse.",
            "Regresa la carne, agrega más soja, vinagre de vino tinto y perejil picado. Mezcla 30 segundos. Sirve de inmediato sobre arroz blanco o papas fritas — el lomo saltado no espera.",
        ],
    },
    {
        id: "albondigas-salsa",
        title: "Albóndigas en salsa de tomate",
        category: "proteinas",
        time: "30 min",
        servings: 3,
        imageQuery: "meatballs tomato sauce pasta",
        ingredients: ["carne", "huevo", "tomate"],
        steps: [
            "Mezcla 400g de carne molida con 1 huevo, 2 cucharadas de pan rallado, sal, pimienta, ajo en polvo y orégano. Trabaja la mezcla lo mínimo posible — amasar en exceso da albóndigas duras. Refrigera 10 minutos para que la mezcla se firme.",
            "Forma albóndigas del tamaño de una pelota de golf con las manos ligeramente húmedas. El tamaño uniforme garantiza cocción pareja.",
            "Dora las albóndigas en sartén con aceite a fuego medio-alto, 1-2 minutos por cada lado hasta sellar toda la superficie. No están completamente cocidas aún — terminarán en la salsa.",
            "Agrega tomate picado o salsa de tomate a la misma sartén, sazona y cocina tapado a fuego medio-bajo 15 minutos. Las albóndigas se terminan de cocer en la salsa absorbiendo sus sabores. Sirve con pasta o arroz.",
        ],
    },

    // ===== PASTA Y ARROZ =====
    {
        id: "arroz-con-pollo",
        title: "Arroz con pollo",
        category: "pasta",
        time: "35 min",
        servings: 3,
        imageQuery: "chicken rice dish one pot",
        ingredients: ["arroz", "pollo", "cebolla"],
        steps: [
            "Corta el pollo en trozos medianos y sazona bien. Dóralo en olla o sartén profunda con aceite a fuego alto 3-4 minutos por lado hasta sellar. El dorado aporta sabor al arroz. Reserva el pollo.",
            "En la misma olla sofríe la cebolla picada fina 3-4 minutos hasta translúcida. Agrega ajo, pimentón en cubos y sofríe 2 minutos más. Este sofrito es la base de sabor del plato.",
            "Agrega el arroz crudo y tuéstalo mezclando 1-2 minutos — verás que cambia a un tono ligeramente blanco opaco. Esto da una textura más suelta al arroz final.",
            "Regresa el pollo, añade agua caliente (proporción 1:1.5 arroz:agua) y una pizca de cúrcuma para dar color. Lleva a hervor, baja el fuego al mínimo, tapa y cocina 18-20 minutos sin destapar. Reposa 5 minutos con fuego apagado antes de servir.",
        ],
    },
    {
        id: "arroz-frito-huevo",
        title: "Arroz frito con huevo",
        category: "pasta",
        time: "12 min",
        servings: 1,
        imageQuery: "fried rice egg wok asian",
        ingredients: ["arroz", "huevo", "cebolla"],
        steps: [
            "El secreto del buen arroz frito: usa arroz del día anterior, frío y suelto. El arroz recién cocido tiene demasiada humedad y queda pegajoso al saltear.",
            "Calienta wok o sartén grande a fuego muy alto. Agrega aceite, sofríe la cebolla picada fina 1 minuto. Agrega el arroz frío y saltea 3-4 minutos sin mover demasiado para que se tueste ligeramente.",
            "Empuja el arroz hacia los bordes del wok, dejando el centro libre. Agrega un poco de aceite al centro y vierte el huevo batido. Revuélvelo hasta que esté a medio cocer y luego intégralo con el arroz.",
            "Sazona con salsa de soja, sal y pimienta. Mezcla todo bien 1 minuto a fuego alto. Sirve de inmediato — el arroz frito se enfría y endurece rápido.",
        ],
    },
    {
        id: "pasta-cremosa",
        title: "Pasta cremosa",
        category: "pasta",
        time: "20 min",
        servings: 2,
        imageQuery: "creamy pasta cheese sauce",
        ingredients: ["pasta", "crema", "queso"],
        steps: [
            "Hierve abundante agua con sal generosa (debe saber salada, como el mar). Cocina la pasta 1 minuto menos del tiempo indicado en el paquete — terminará de cocerse en la salsa. Guarda 1 taza del agua de cocción antes de escurrir.",
            "Mientras la pasta cuece, calienta la crema en sartén amplia a fuego medio hasta que empiece a burbujear suavemente. No la dejes hervir fuerte o se reduce demasiado.",
            "Agrega la mitad del queso rallado a la crema, moviendo hasta obtener una salsa lisa. Si queda muy espesa, añade un chorrito del agua de pasta reservada — el almidón que contiene hace la salsa más sedosa.",
            "Agrega la pasta escurrida directamente a la sartén con la salsa. Mezcla bien a fuego bajo 1-2 minutos hasta que la pasta absorba parte de la salsa. Sirve de inmediato con el queso restante por encima y pimienta negra generosa.",
        ],
    },
    {
        id: "pasta-atun-limon",
        title: "Pasta de atún y limón",
        category: "pasta",
        time: "15 min",
        servings: 2,
        imageQuery: "tuna lemon pasta light",
        ingredients: ["pasta", "atun", "limon"],
        steps: [
            "Cuece la pasta en agua muy salada hasta al dente. Esta receta es rápida: prepara todos los ingredientes mientras la pasta hierve.",
            "Escurre el atún y desmenuza con tenedor. En un bowl grande, mezcla el atún con el jugo y ralladura de 1 limón, aceite de oliva generoso, sal y pimienta. La ralladura de limón es clave — aporta aroma que el jugo solo no da.",
            "Escurre la pasta reservando 3-4 cucharadas del agua de cocción. Agrega la pasta caliente al bowl con el atún.",
            "Mezcla bien — el calor de la pasta calienta el atún ligeramente. Si queda seco, añade el agua de pasta reservada de a poco. Ajusta limón, sal y aceite. Sirve con perejil fresco si tienes.",
        ],
    },
    {
        id: "pasta-pollo-crema",
        title: "Pasta de pollo y crema",
        category: "pasta",
        time: "25 min",
        servings: 2,
        imageQuery: "chicken cream pasta dinner",
        ingredients: ["pasta", "pollo", "crema"],
        steps: [
            "Cuece la pasta en agua abundante con sal. Reserva una taza del agua de cocción antes de escurrir — es el ingrediente secreto para una salsa perfecta.",
            "Corta el pollo en cubos de 2cm y sazona bien. Sella en sartén con aceite a fuego alto 4-5 minutos hasta dorar todos los lados. Retira y reserva.",
            "En la misma sartén, agrega la crema a fuego medio. Raspa el fondo para incorporar los jugos del pollo — ahí está todo el sabor. Deja que la crema reduzca 3 minutos hasta espesar ligeramente.",
            "Regresa el pollo a la sartén, agrega la pasta escurrida y mezcla bien. Ajusta la consistencia con el agua de pasta reservada. Sazona con sal, pimienta y orégano. Sirve de inmediato con queso rallado.",
        ],
    },
    {
        id: "risotto-champinon",
        title: "Risotto de champiñón",
        category: "pasta",
        time: "35 min",
        servings: 2,
        imageQuery: "mushroom risotto creamy italian",
        ingredients: ["arroz", "champinon", "crema"],
        steps: [
            "Calienta caldo de verduras o de pollo en una olla pequeña — el caldo siempre debe estar caliente cuando se añade al risotto. Lamina los champiñones y saltéalos en sartén con mantequilla a fuego alto hasta dorar bien. Reserva.",
            "En una olla amplia, sofríe media cebolla picada muy fina con mantequilla hasta transparente. Agrega el arroz para risotto (arborio o carnaroli) y tuesta 2 minutos revolviendo.",
            "Agrega el caldo caliente un cucharón a la vez, revolviendo constantemente a fuego medio. Solo agrega el siguiente cucharón cuando el anterior haya sido absorbido completamente. Este proceso tarda 18-20 minutos.",
            "Cuando el arroz esté al dente, retira del fuego. Agrega los champiñones salteados, 2 cucharadas de crema y mantequilla fría. Mezcla vigorosamente — este es el 'mantecato', que da la cremosidad característica. Sirve de inmediato.",
        ],
    },

    // ===== SOPAS Y CREMAS =====
    {
        id: "crema-zapallo",
        title: "Crema de zapallo",
        category: "sopas",
        time: "30 min",
        servings: 3,
        imageQuery: "pumpkin cream soup bowl",
        ingredients: ["zapallo", "crema", "cebolla"],
        steps: [
            "Corta 500g de zapallo en cubos de 3cm. No es necesario pelarlo muy prolijamente, ya que todo se procesará. Pica media cebolla en trozos grandes.",
            "Sofríe la cebolla en olla con aceite a fuego medio 4 minutos hasta ablandar. Agrega el zapallo y revuelve 2 minutos para que tome un poco de color — esto profundiza el sabor de la crema.",
            "Cubre justo con agua fría o caldo (unos 500ml). Lleva a hervor, baja el fuego y cocina tapado 15-18 minutos hasta que el zapallo se pinche fácilmente con un tenedor.",
            "Procesa con minipimer o licuadora hasta obtener una crema completamente lisa. Agrega la crema de leche, sal y pimienta. Calienta 2 minutos más sin hervir. Ajusta consistencia con agua si quedó muy espesa. Sirve con un hilo de crema encima.",
        ],
    },
    {
        id: "sopa-verduras",
        title: "Sopa de verduras",
        category: "sopas",
        time: "30 min",
        servings: 3,
        imageQuery: "vegetable soup bowl carrot potato",
        ingredients: ["zanahoria", "papa", "apio"],
        steps: [
            "Corta la zanahoria en rodajas de 1cm, la papa en cubos de 2cm y el apio en trozos de 2cm. El corte similar en tamaño asegura que todo se cocine al mismo tiempo.",
            "Sofríe en olla con aceite a fuego medio: primero la zanahoria y apio 3 minutos, luego la papa. Este paso potencia el sabor final comparado con hervir directamente en agua.",
            "Cubre con agua caliente (1.5 litros) y añade sal, pimienta, 1 hoja de laurel y orégano. Lleva a hervor, baja el fuego y cocina tapado 20 minutos hasta que todas las verduras estén tiernas.",
            "Ajusta la sazón. Para una sopa más sustanciosa, tritura parte de las verduras contra la pared de la olla con un tenedor — esto espesa el caldo naturalmente. Sirve caliente con pan.",
        ],
    },
    {
        id: "cazuela-chilena",
        title: "Cazuela chilena",
        category: "sopas",
        time: "45 min",
        servings: 2,
        imageQuery: "chicken potato stew soup bowl",
        ingredients: ["pollo", "papa", "zapallo"],
        steps: [
            "Usa trozos de pollo con hueso (muslo, contramuslo, alas) — dan mucho más sabor al caldo que la pechuga sola. Sazona bien con sal y pimienta y dora 3 minutos por lado en la olla.",
            "Cubre con 1 litro de agua fría, añade 1 hoja de laurel, orégano, 1 diente de ajo y lleva a hervor. Retira la espuma que sube a la superficie los primeros 5 minutos — esto da un caldo limpio.",
            "Agrega la papa cortada en trozos grandes y el zapallo en cuadrados de 5cm. Baja el fuego y cocina tapado 25-30 minutos hasta que las verduras estén tiernas pero sin deshacerse.",
            "Ajusta la sal y agrega choclo si tienes. Sirve en bowls hondos con el trozo de pollo, las verduras y bastante caldo. El caldo de cazuela debe ser limpio y transparente — si está turbio, cocinaste con fuego muy alto.",
        ],
    },
    {
        id: "sopa-lentejas",
        title: "Sopa de lentejas",
        category: "sopas",
        time: "40 min",
        servings: 3,
        imageQuery: "lentil soup carrot onion bowl",
        ingredients: ["lenteja", "zanahoria", "cebolla"],
        steps: [
            "Enjuaga las lentejas bajo agua fría y descarta las que floten (están en mal estado). No es necesario remojarlas si usas lentejas rojas o pardas — se cocinan directo.",
            "Sofríe cebolla picada fina con zanahoria en cubos pequeños en olla con aceite a fuego medio 5 minutos hasta que la cebolla esté translúcida. Agrega ajo, comino y páprika, sofríe 1 minuto más.",
            "Agrega las lentejas enjuagadas y cubre con 1 litro de agua o caldo caliente. Añade sal y una hoja de laurel. Lleva a hervor, baja el fuego y cocina tapado 25-30 minutos hasta que las lentejas estén completamente tiernas.",
            "Para una sopa más cremosa, tritura 1/3 de la sopa con minipimer y luego mezcla. Ajusta la sazón con sal, limón y pimienta. Sirve con un chorrito de aceite de oliva y, si tienes, cilantro fresco.",
        ],
    },

    // ===== SNACKS Y COMPLEMENTOS =====
    {
        id: "croquetas-papa-queso",
        title: "Croquetas de papa y queso",
        category: "snacks",
        time: "30 min",
        servings: 3,
        imageQuery: "potato cheese croquettes fried",
        ingredients: ["papa", "queso", "huevo"],
        steps: [
            "Cuece 400g de papas con piel en agua salada hasta que estén completamente tiernas. Pélalas calientes (más fácil) y tritúralas de inmediato — el puré de papa frío queda gomoso.",
            "Mezcla el puré con queso rallado generoso, 1 yema de huevo, sal, pimienta y nuez moscada. La mezcla debe estar fría antes de formar las croquetas — refrigera 20 minutos.",
            "Con las manos ligeramente húmedas, forma cilindros de 6cm. Pásalos por huevo batido y luego por pan rallado, asegurando cobertura completa. Refrigera 10 minutos más para que el empanado adhiera bien.",
            "Fríe en aceite abundante a 175°C (una miga de pan debe chisporrotear al caer). Cocina 3-4 croquetas a la vez 3-4 minutos hasta que estén doradas uniformemente. Escurre en papel absorbente y sirve de inmediato.",
        ],
    },
    {
        id: "gratin-coliflor-queso",
        title: "Gratín de coliflor y queso",
        category: "snacks",
        time: "30 min",
        servings: 3,
        imageQuery: "cauliflower cheese gratin baked",
        ingredients: ["coliflor", "queso", "crema"],
        steps: [
            "Precalienta el horno a 200°C. Separa la coliflor en floretes medianos. Blanquéalos en agua hirviendo con sal 5 minutos hasta que estén tiernos pero con mordida. Escurre bien.",
            "Mezcla la crema con la mitad del queso rallado, sal, pimienta y nuez moscada. Esta mezcla será la salsa bechamel exprés.",
            "Distribuye los floretes de coliflor en una fuente para horno engrasada. Vierte la mezcla de crema uniformemente y esparce el queso restante por encima.",
            "Hornea 20-25 minutos hasta que la superficie esté bien dorada y burbujee. Los últimos 5 minutos, sube la temperatura a 220°C o activa el grill para una costra más crujiente. Deja reposar 5 minutos antes de servir.",
        ],
    },
    {
        id: "pure-papa-queso",
        title: "Puré de papa y queso",
        category: "snacks",
        time: "25 min",
        servings: 2,
        imageQuery: "mashed potato cheese creamy",
        ingredients: ["papa", "leche", "queso"],
        steps: [
            "Pela y corta 400g de papas en cubos del mismo tamaño. Cuécelas partiendo de agua fría con sal — esto da una cocción más pareja que echarlas al agua hirviendo.",
            "Cuece 20-25 minutos hasta que un tenedor entre sin resistencia. Escurre completamente y vuelve a la olla vacía a fuego muy bajo 1 minuto para evaporar el exceso de humedad — esto da un puré más seco y cremoso.",
            "Aplasta las papas con un pisapapas o tenedor (nunca con licuadora o minipimer — activa el gluten y queda gomoso). Añade mantequilla fría cortada en cubos y mezcla hasta incorporar.",
            "Agrega leche caliente de a poco hasta obtener la consistencia deseada. Incorpora el queso rallado y mezcla. Sazona con sal, pimienta blanca y nuez moscada. Sirve de inmediato — el puré se espesa al enfriarse.",
        ],
    },
    {
        id: "sopaipillas",
        title: "Sopaipillas",
        category: "snacks",
        time: "35 min",
        servings: 4,
        imageQuery: "fried pumpkin dough pastry chilean",
        ingredients: ["zapallo", "harina", "mantequilla"],
        steps: [
            "Cuece 200g de zapallo en cubos al vapor o microondas hasta que esté completamente blando. Aplástalo bien y déjalo enfriar completamente — el zapallo caliente arruina la textura de la masa.",
            "Mezcla el puré de zapallo con 250g de harina, 1 cucharadita de sal, 30g de mantequilla blanda y 1 cucharadita de polvos de hornear. Integra sin amasar demasiado — solo hasta que no queden grumos secos. La masa debe ser blanda pero no pegajosa.",
            "Estira la masa sobre superficie enharinada a 5mm de grosor. Corta círculos de 8-10cm con un cortador o vaso. Pincha el centro con un tenedor 3-4 veces para que no se inflen al freír.",
            "Fríe en aceite abundante bien caliente (175°C) 2-3 minutos por lado hasta que estén doradas. No frías demasiadas a la vez o baja la temperatura del aceite. Escurre en papel absorbente. Sirve con pebre o chancaca.",
        ],
    },
    {
        id: "guacamole-tostadas",
        title: "Guacamole con tostadas",
        category: "snacks",
        time: "10 min",
        servings: 2,
        imageQuery: "guacamole avocado chips toast",
        ingredients: ["palta", "tomate", "limon"],
        steps: [
            "Usa paltas maduras — deben ceder al presionar suavemente con el pulgar. Córtalas a la mitad, retira el carozo y extrae la pulpa con una cuchara grande.",
            "Aplasta la palta con tenedor sobre un plato o tabla. No uses licuadora ni batidora — el guacamole tiene que tener textura irregular, no ser un puré liso. Deja algunos trozos.",
            "Agrega el tomate en cubos muy pequeños (sin semillas para evitar que aguade el guacamole), jugo de limón generoso, sal y cilantro picado si tienes. Mezcla suavemente con tenedor.",
            "Prueba la sazón: debe ser equilibrado entre ácido, salado y el sabor neutro de la palta. Cubre con papel film directamente sobre la superficie del guacamole (el contacto con el aire lo oxida). Sirve de inmediato con tostadas o chips.",
        ],
    },
    {
        id: "hummus-casero",
        title: "Hummus casero",
        category: "snacks",
        time: "10 min",
        servings: 3,
        imageQuery: "homemade hummus chickpea dip",
        ingredients: ["garbanzo", "limon", "aceite"],
        steps: [
            "Escurre y enjuaga una lata de garbanzos cocidos. Para un hummus más suave, pela los garbanzos uno a uno (la piel exterior se quita fácilmente apretando suavemente). Este paso marca una diferencia notable en la textura.",
            "Agrega los garbanzos a la procesadora con 2 cucharadas de tahini (pasta de sésamo), jugo de 1 limón, 1 diente de ajo pequeño, sal y 2 cucharadas de agua fría o hielo.",
            "Procesa 3-4 minutos a máxima velocidad hasta que quede completamente liso. Si hay procesadora disponible, el hummus perfecto se procesa mucho más tiempo de lo que parece necesario. Añade agua de a poco si queda muy espeso.",
            "Prueba y ajusta limón y sal. Sirve en bowl, haz un hueco en el centro y llénalo con aceite de oliva extra virgen. Espolvorea páprika ahumada y sésamo tostado. Acompaña con pan de pita, tostadas o verduras crudas.",
        ],
    },

    // ===== BEBIDAS ALCOHOLICAS =====
    {
        id: "piscola-clasica",
        title: "Piscola clásica",
        category: "cocteles",
        time: "5 min",
        servings: 1,
        imageQuery: "rum cola cocktail ice glass",
        ingredients: ["pisco", "coca cola", "limon"],
        steps: [
            "Enfría el vaso llenándolo de hielo 1 minuto y botando el agua. Los tragos siempre saben mejor en vaso frío.",
            "Llena el vaso de hielo picado o en cubos hasta el borde. Usa bastante hielo — enfría rápido la bebida y la diluye lentamente.",
            "Agrega pisco en proporción 1:3 (1 parte pisco, 3 cola). Para una piscola más fuerte usa 1:2. Vierte la cola por el costado del vaso con suavidad para conservar el gas.",
            "Exprime medio limón por encima. Revuelve solo 2-3 veces con un sorbete — la piscola no necesita mezcla agresiva. Sirve inmediatamente.",
        ],
    },
    {
        id: "pisco-sour",
        title: "Pisco Sour",
        category: "cocteles",
        time: "8 min",
        servings: 1,
        imageQuery: "pisco sour cocktail foam glass",
        ingredients: ["pisco", "limon", "huevo"],
        steps: [
            "Enfría la copa en el congelador 10 minutos. Un Pisco Sour siempre se sirve en copa fría.",
            "En una coctelera sin hielo, mezcla 60ml de pisco, 30ml de jugo de limón recién exprimido, 20ml de almíbar simple y 1 clara de huevo. Este 'dry shake' emulsiona la clara para crear la espuma.",
            "Cierra la coctelera y agita enérgicamente 15 segundos. Luego agrega hielo y agita 10 segundos más. El sonido del hielo cambia cuando la bebida está bien fría.",
            "Cuela con colador fino en la copa fría. La espuma debe quedar por encima. Agrega 2-3 gotas de amargo de Angostura formando un patrón en la espuma. Sirve inmediatamente — la espuma dura poco.",
        ],
    },
    {
        id: "borgona-chilena",
        title: "Borgoña chilena",
        category: "cocteles",
        time: "15 min",
        servings: 4,
        imageQuery: "red wine strawberry punch drink",
        ingredients: ["vino", "frutilla", "azucar"],
        steps: [
            "Lava 300g de frutillas y córtalas en mitades. En un bowl, mezcla las frutillas con 3 cucharadas de azúcar y deja macerar 10-15 minutos. El azúcar extrae el jugo de las frutillas, que es lo que da color y sabor a la borgoña.",
            "Cuando las frutillas hayan soltado bastante jugo, aplasta ligeramente unas pocas con un tenedor para intensificar el sabor — pero deja la mayoría enteras para la presentación.",
            "Vierte 750ml de vino tinto frío (un carménère o cabernet joven funciona muy bien). No uses un vino muy añejo — la borgoña es un trago informal.",
            "Mezcla suavemente y prueba. Si necesita más dulzor, añade azúcar; si está muy dulce, añade más vino. Sirve de inmediato con hielo en cada vaso y algunas frutillas encima.",
        ],
    },
    {
        id: "navegado-chileno",
        title: "Navegado chileno",
        category: "cocteles",
        time: "15 min",
        servings: 3,
        imageQuery: "mulled wine orange cinnamon hot",
        ingredients: ["vino", "naranja", "canela"],
        steps: [
            "Vierte 750ml de vino tinto en una olla. Usa un vino joven y frutal — no un vino caro. Calienta a fuego medio-bajo sin dejar que hierva (el alcohol se evapora y pierde sabor).",
            "Agrega 2 ramas de canela, 3 clavos de olor, 2 cucharadas de azúcar y las rodajas de 1 naranja con cáscara. La cáscara aporta aceites aromáticos.",
            "Mantén a fuego muy bajo 10-12 minutos revolviendo ocasionalmente. El vino debe humearse pero nunca burbujear — si ves burbujas, baja inmediatamente el fuego.",
            "Prueba el dulzor y ajusta con más azúcar si es necesario. Sirve en taza o pocillo resistente al calor con un trozo de naranja. Advierte a tus invitados que la taza estará caliente.",
        ],
    },
    {
        id: "terremoto",
        title: "Terremoto",
        category: "cocteles",
        time: "5 min",
        servings: 1,
        imageQuery: "wine ice cream float cocktail",
        ingredients: ["vino", "helado", "granadina"],
        steps: [
            "Usa un vaso muy grande (tipo jarro de cerveza o vaso de 500ml). El terremoto es grande por definición.",
            "Sirve vino pipeño blanco o chicha bien fría hasta 3/4 del vaso. Si no tienes pipeño, usa un vino blanco joven y dulce muy frío.",
            "Con una cuchara de helados, agrega 1-2 bolas de helado de piña directamente en el vino. El contraste calor-frío hará que el helado se derrita lentamente.",
            "Agrega un chorro generoso de granadina por encima del helado y sirve de inmediato con sorbete. El terremoto debe beberse de inmediato antes de que el helado se derrita completamente.",
        ],
    },
    {
        id: "clery-chileno",
        title: "Clery chileno",
        category: "cocteles",
        time: "20 min",
        servings: 4,
        imageQuery: "white wine strawberry punch cold",
        ingredients: ["vino", "frutilla", "limon"],
        steps: [
            "Lava y corta en mitades 200g de frutillas maduras. Mezcla con 2 cucharadas de azúcar y el jugo de 1 limón. Deja macerar 15 minutos hasta que suelten su jugo.",
            "Aplasta suavemente algunas frutillas con un tenedor para intensificar el color y sabor de la maceración.",
            "Vierte 750ml de vino blanco muy frío (sauvignon blanc o chardonnay joven funcionan bien). El vino debe estar refrigerado al menos 2 horas antes.",
            "Mezcla suavemente, prueba el dulzor y ajusta. Refrigera 15-20 minutos para que los sabores se integren. Sirve en copa o vaso con hielo y algunas frutillas.",
        ],
    },
    {
        id: "chela-limon",
        title: "Chela con limón",
        category: "cocteles",
        time: "3 min",
        servings: 1,
        imageQuery: "beer lemon glass cold drink",
        ingredients: ["cerveza", "limon", "sal"],
        steps: [
            "Usa un vaso helado o uno pasado por el congelador 5 minutos. La cerveza con limón siempre sabe mejor en vaso frío.",
            "Frota el borde del vaso con medio limón y pásalo por sal para hacer un borde salado. Esto es opcional pero potencia mucho la experiencia.",
            "Sirve la cerveza bien fría inclinando el vaso para reducir la espuma.",
            "Exprime el jugo de medio limón directo en la cerveza y revuelve suavemente con el dedo o sorbete. La proporción correcta: la cerveza debe dominar, el limón solo la refresca. Sirve de inmediato.",
        ],
    },
    {
        id: "michelada",
        title: "Michelada",
        category: "cocteles",
        time: "5 min",
        servings: 1,
        imageQuery: "michelada beer tomato juice spicy",
        ingredients: ["cerveza", "limon", "tomate"],
        steps: [
            "Prepara el vaso: frota el borde con limón y pásalo por una mezcla de sal y chile en polvo para hacer un borde condimentado.",
            "Agrega al vaso: 30ml de jugo de limón, 50ml de jugo de tomate, 5ml de salsa inglesa (Worcestershire), un toque de tabasco y sal. Mezcla bien.",
            "Agrega hielo al vaso hasta 3/4. Vierte la cerveza fría lentamente por el costado para no perder el gas.",
            "Revuelve suavemente con un sorbete solo 2-3 veces. Prueba y ajusta el picante con más tabasco si lo prefieres. Decora con una rodaja de limón en el borde.",
        ],
    },
    {
        id: "sangria-rapida",
        title: "Sangría rápida",
        category: "cocteles",
        time: "10 min + reposo",
        servings: 4,
        imageQuery: "sangria red wine fruit orange",
        ingredients: ["vino", "naranja", "manzana"],
        steps: [
            "Corta media naranja con cáscara en rodajas finas y media manzana en cubos pequeños. Las frutas con cáscara aportan más aroma a la sangría.",
            "En una jarra, mezcla las frutas con 2 cucharadas de azúcar y deja macerar 5 minutos. Añade 60ml de brandy o pisco si tienes — esto potencia el sabor enormemente.",
            "Vierte 750ml de vino tinto y revuelve bien hasta disolver el azúcar. Puedes añadir 100ml de jugo de naranja natural para más fruta.",
            "Refrigera al menos 1 hora (mejor 4 horas). La sangría mejora con el reposo a medida que el vino se impregna de los sabores de la fruta. Sirve con mucho hielo y las frutas maceradas.",
        ],
    },

];

export const FALLBACK_RECIPES = [

    // ===== FALLBACK: usados cuando no hay coincidencias en el catalogo =====
    {
        id: "wrap-verduras",
        title: "Wrap de verduras",
        category: "sandwiches",
        time: "10 min",
        servings: 1,
        imageQuery: "vegetable wrap tortilla",
        ingredients: ["pan", "tomate", "cebolla"],
        steps: [
            "Calienta una tortilla en sartén seca 30 segundos por lado hasta que esté flexible con manchas doradas.",
            "Corta el tomate en rodajas y la cebolla en pluma fina. Si la cebolla es muy picante, remójala en agua fría 5 minutos.",
            "Distribuye las verduras en el centro de la tortilla. Añade cualquier acompañamiento que tengas: mayonesa, palta, lechuga.",
            "Dobla los extremos laterales y enrolla firmemente. Corta en diagonal y sirve.",
        ],
    },
    {
        id: "tostadas-palta",
        title: "Tostadas con palta",
        category: "sandwiches",
        time: "8 min",
        servings: 1,
        imageQuery: "avocado toast bread",
        ingredients: ["pan", "palta", "aceite"],
        steps: [
            "Tuesta el pan a tu nivel de dorado preferido. Pan más oscuro aguanta mejor los toppings húmedos sin reblandecerse.",
            "Aplasta la palta con tenedor, añade sal, pimienta y jugo de limón. La palta debe tener textura irregular, no ser un puré.",
            "Unta la palta generosamente sobre el pan. La capa debe ser gruesa — una capa fina se pierde bajo otros toppings.",
            "Termina con aceite de oliva en hilo, sal de mar en escamas y pimienta negra. Sirve de inmediato.",
        ],
    },
    {
        id: "bowl-yogur-fruta-fallback",
        title: "Bowl de yogur y fruta",
        category: "jugos",
        time: "8 min",
        servings: 1,
        imageQuery: "yogurt fruit bowl healthy",
        ingredients: ["yogur", "platano", "frutilla"],
        steps: [
            "Sirve 200g de yogur griego en un bowl amplio y frío.",
            "Corta el plátano en rodajas y las frutillas en mitades.",
            "Distribuye la fruta visualmente sobre el yogur en secciones separadas.",
            "Agrega miel, granola y semillas si tienes. Come de inmediato.",
        ],
    },
    {
        id: "sandwich-queso-tomate",
        title: "Sándwich de queso y tomate",
        category: "sandwiches",
        time: "8 min",
        servings: 1,
        imageQuery: "cheese tomato sandwich",
        ingredients: ["pan", "queso", "tomate"],
        steps: [
            "Unta mantequilla por fuera del pan armado para dorar en sartén al estilo grilled cheese.",
            "Coloca láminas de queso y rodajas de tomate seco en papel absorbente en el interior.",
            "Cocina en sartén a fuego medio 2-3 minutos por lado hasta que el queso esté fundido y el pan dorado.",
            "Deja reposar 1 minuto, corta en diagonal y sirve.",
        ],
    },
    {
        id: "huevos-a-la-plancha",
        title: "Huevos a la plancha",
        category: "proteinas",
        time: "8 min",
        servings: 1,
        imageQuery: "fried eggs breakfast pan",
        ingredients: ["huevo", "mantequilla", "pan"],
        steps: [
            "Tuesta el pan y resérvalo caliente tapado con un plato.",
            "Calienta sartén a fuego medio con mantequilla. Cuando forme espuma, baja el fuego.",
            "Rompe los huevos con cuidado de no romper la yema. Cocina 3-4 minutos para yema líquida o 5-6 para más firme.",
            "Sazona con sal y pimienta solo al final — la sal sobre la yema la endurece si se agrega antes. Sirve sobre el pan tostado.",
        ],
    },
    {
        id: "ensalada-express",
        title: "Ensalada exprés",
        category: "ensaladas",
        time: "8 min",
        servings: 1,
        imageQuery: "fresh green salad bowl",
        ingredients: ["lechuga", "tomate", "pepino"],
        steps: [
            "Lava la lechuga y sécala completamente — el agua diluye el aliño y hace la ensalada aguada.",
            "Corta el tomate en cuñas y el pepino en rodajas.",
            "Mezcla en bowl y aliña solo al momento de servir con aceite de oliva, limón, sal y pimienta.",
            "Mezcla suavemente para que el aliño cubra todas las hojas sin romperlas.",
        ],
    },
    {
        id: "yogur-manzana",
        title: "Yogur con manzana",
        category: "jugos",
        time: "5 min",
        servings: 1,
        imageQuery: "yogurt apple honey bowl",
        ingredients: ["yogur", "manzana", "miel"],
        steps: [
            "Sirve el yogur en un bowl. El yogur griego da mejor textura.",
            "Corta la manzana en cubos pequeños con cáscara para más fibra y color.",
            "Distribuye la manzana sobre el yogur.",
            "Termina con un hilo de miel y canela si tienes. Come de inmediato.",
        ],
    },
    {
        id: "pan-jamon-queso",
        title: "Pan con jamón y queso",
        category: "sandwiches",
        time: "8 min",
        servings: 1,
        imageQuery: "ham cheese sandwich toasted",
        ingredients: ["pan", "jamon", "queso"],
        steps: [
            "Arma el sándwich con 2-3 láminas de jamón y queso en láminas.",
            "Unta mantequilla por fuera de ambas tapas para dorar en sartén.",
            "Cocina a fuego medio 2-3 minutos por lado hasta que el queso esté fundido y el pan dorado.",
            "Deja reposar 1 minuto antes de cortar.",
        ],
    },
    {
        id: "revuelto-rapido",
        title: "Revuelto rápido",
        category: "proteinas",
        time: "10 min",
        servings: 1,
        imageQuery: "scrambled eggs tomato onion",
        ingredients: ["huevo", "cebolla", "tomate"],
        steps: [
            "Sofríe la cebolla picada fina en sartén con aceite 3 minutos a fuego medio.",
            "Agrega el tomate en cubos y saltea 2 minutos hasta que suelte su jugo.",
            "Bate los huevos con sal y pimienta y viértelos sobre las verduras.",
            "Mueve suavemente desde los bordes hacia el centro hasta que queden cremosos. Retira del fuego antes de que terminen de cuajar.",
        ],
    },
    {
        id: "licuado-leche-platano",
        title: "Licuado de leche y plátano",
        category: "jugos",
        time: "5 min",
        servings: 1,
        imageQuery: "banana milk smoothie drink",
        ingredients: ["leche", "platano", "yogur"],
        steps: [
            "Pela 1 plátano maduro y córtalo en trozos.",
            "Agrega el plátano, 200ml de leche y 2 cucharadas de yogur a la licuadora.",
            "Licua 30 segundos a velocidad alta hasta que esté completamente liso.",
            "Prueba el dulzor — si necesita más, añade 1 cucharadita de miel. Sirve frío de inmediato.",
        ],
    },
    {
        id: "salteado-basico",
        title: "Salteado básico",
        category: "snacks",
        time: "12 min",
        servings: 2,
        imageQuery: "vegetable stir fry colorful",
        ingredients: ["zanahoria", "cebolla", "pimenton"],
        steps: [
            "Corta todas las verduras en tiras finas y uniformes. Ten todo listo antes de encender el fuego.",
            "Calienta wok o sartén a fuego muy alto hasta que humee. Agrega aceite con alto punto de humo.",
            "Saltea la cebolla 1 minuto, luego el pimentón 1 minuto, y finalmente la zanahoria 2 minutos sin mover demasiado.",
            "Sazona con soja, sal y pimienta. Sirve de inmediato como acompañamiento o base para otros platos.",
        ],
    },
    {
        id: "sopa-rapida-papa",
        title: "Sopa rápida de papa",
        category: "sopas",
        time: "20 min",
        servings: 2,
        imageQuery: "potato cream soup bowl",
        ingredients: ["papa", "leche", "cebolla"],
        steps: [
            "Sofríe media cebolla picada en olla con aceite 3 minutos. Agrega 2 papas peladas en cubos y revuelve 1 minuto.",
            "Cubre con agua caliente y sal. Cocina 15 minutos hasta que las papas estén completamente tiernas.",
            "Procesa con minipimer hasta obtener una crema completamente lisa.",
            "Agrega leche caliente, ajusta la consistencia y sazón. Sirve con un hilo de aceite de oliva.",
        ],
    },
    {
        id: "tostada-huevo-palta",
        title: "Tostada de huevo y palta",
        category: "sandwiches",
        time: "12 min",
        servings: 1,
        imageQuery: "avocado egg toast breakfast",
        ingredients: ["pan", "huevo", "palta"],
        steps: [
            "Tuesta el pan hasta que esté bien dorado y crujiente.",
            "Aplasta la palta con tenedor, añade sal, limón y pimienta.",
            "Cuece el huevo a tu gusto: pochado, frito o revuelto.",
            "Unta la palta sobre el pan y coloca el huevo encima. Sazona con sal en escamas y pimienta.",
        ],
    },
    {
        id: "rollitos-pavo-queso",
        title: "Rollitos de pavo y queso",
        category: "snacks",
        time: "8 min",
        servings: 1,
        imageQuery: "turkey cheese rolls cucumber snack",
        ingredients: ["pavo", "queso", "pepino"],
        steps: [
            "Corta el pepino en bastones de 8cm de largo y 1cm de grosor.",
            "Extiende una lámina de pavo y coloca una lámina de queso encima.",
            "Coloca un bastón de pepino en el extremo del pavo-queso y enrolla firmemente.",
            "Asegura con un palillo si es necesario. Sirve frío como snack o entrada.",
        ],
    },
    {
        id: "ensalada-pepino-yogur",
        title: "Ensalada de pepino y yogur",
        category: "ensaladas",
        time: "10 min",
        servings: 2,
        imageQuery: "cucumber yogurt salad fresh",
        ingredients: ["pepino", "yogur", "limon"],
        steps: [
            "Corta el pepino en rodajas finas de 3mm. Si el pepino es amargo, pela primero.",
            "Mezcla 150g de yogur griego con jugo de limón, sal, pimienta y ajo en polvo si tienes.",
            "Combina las rodajas de pepino con el aliño de yogur.",
            "Refrigera 10 minutos para que se integren los sabores. Sirve frío con eneldo o menta si tienes.",
        ],
    },
    {
        id: "plato-frio-queso-tomate",
        title: "Plato frío de queso y tomate",
        category: "snacks",
        time: "8 min",
        servings: 1,
        imageQuery: "cheese tomato plate food",
        ingredients: ["queso", "tomate", "aceite"],
        steps: [
            "Usa queso y tomate a temperatura ambiente para que los sabores sean más intensos.",
            "Corta el queso en láminas de 8mm y el tomate en rodajas de igual grosor.",
            "Alterna las rodajas en un plato inclinadas ligeramente unas sobre otras.",
            "Aliña con aceite de oliva extra virgen, sal de mar en escamas y pimienta negra. Sirve de inmediato.",
        ],
    },
];
